SELECT CTD.CONCEPT_CODE AS CASNR,
       INGREDIENT.CONCEPT_ID
FROM @vocab.CONCEPT CTD
LEFT OUTER JOIN @vocab.CONCEPT_RELATIONSHIP MAPSTO
    ON CTD.CONCEPT_ID = MAPSTO.CONCEPT_ID_1
INNER JOIN @vocab.CONCEPT INGREDIENT
    ON MAPSTO.CONCEPT_ID_2 = INGREDIENT.CONCEPT_ID
WHERE CTD.VOCABULARY_ID = 'CTD'
AND   CTD.INVALID_REASON IS NULL
AND   INGREDIENT.DOMAIN_ID = 'Drug'
AND   UPPER(INGREDIENT.VOCABULARY_ID) LIKE 'RXNORM%'
AND   INGREDIENT.CONCEPT_CLASS_ID = 'Ingredient'
AND   INGREDIENT.STANDARD_CONCEPT = 'S'
AND   INGREDIENT.INVALID_REASON IS NULL
ORDER BY INGREDIENT.CONCEPT_ID ASC;