WITH UNITS AS (
    SELECT DISTINCT AMOUNT_UNIT.*
    FROM @vocab.DRUG_STRENGTH
      LEFT OUTER JOIN @vocab.CONCEPT AMOUNT_UNIT
        ON AMOUNT_UNIT_CONCEPT_ID = CONCEPT_ID
  UNION ALL
    SELECT DISTINCT NUMERATOR_UNIT.*
    FROM @vocab.DRUG_STRENGTH
      LEFT OUTER JOIN @vocab.CONCEPT NUMERATOR_UNIT
        ON NUMERATOR_UNIT_CONCEPT_ID = CONCEPT_ID
  UNION ALL
    SELECT DISTINCT DENOMINATOR_UNIT.*
    FROM @vocab.DRUG_STRENGTH
      LEFT OUTER JOIN @vocab.CONCEPT DENOMINATOR_UNIT
        ON DENOMINATOR_UNIT_CONCEPT_ID = CONCEPT_ID
)
SELECT DISTINCT *
FROM UNITS
WHERE DOMAIN_ID = 'Unit'
AND   CONCEPT_CLASS_ID = 'Unit'
AND   STANDARD_CONCEPT = 'S'
ORDER BY CONCEPT_NAME