SELECT DRUG.CONCEPT_ID AS DRUG_CONCEPT_ID,
       DRUG.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
       DRUG.DOMAIN_ID AS DRUG_DOMAIN_ID,
       DRUG.VOCABULARY_ID AS DRUG_VOCABULARY_ID,
       DRUG.CONCEPT_CLASS_ID AS DRUG_CONCEPT_CLASS_ID,
       DRUG.STANDARD_CONCEPT AS DRUG_STANDARD_CONCEPT,
       DRUG.CONCEPT_CODE AS DRUG_CONCEPT_CODE,
       DRUG.VALID_START_DATE AS DRUG_VALID_START_DATE,
       DRUG.VALID_END_DATE AS DRUG_VALID_END_DATE, 
       DRUG.INVALID_REASON AS DRUG_INVALID_REASON,
       INGREDIENT_CONCEPT_ID,
       AMOUNT_VALUE,
       AMOUNT_UNIT_CONCEPT_ID,
       NUMERATOR_VALUE,
       NUMERATOR_UNIT_CONCEPT_ID,
       DENOMINATOR_VALUE,
       DENOMINATOR_UNIT_CONCEPT_ID,
       FORM.CONCEPT_ID AS FORM_CONCEPT_ID
FROM @vocab.DRUG_STRENGTH
  INNER JOIN @vocab.CONCEPT DRUG
    ON DRUG_STRENGTH.DRUG_CONCEPT_ID = DRUG.CONCEPT_ID
  LEFT JOIN @vocab.CONCEPT_RELATIONSHIP
    ON CONCEPT_RELATIONSHIP.CONCEPT_ID_1 = DRUG.CONCEPT_ID
  LEFT JOIN @vocab.CONCEPT FORM
    ON FORM.CONCEPT_ID = CONCEPT_RELATIONSHIP.CONCEPT_ID_2
WHERE CONCEPT_RELATIONSHIP.RELATIONSHIP_ID = 'RxNorm has dose form'
AND   DRUG_STRENGTH.INVALID_REASON IS NULL
AND   DRUG.CONCEPT_CLASS_ID = 'Clinical Drug'
AND   DRUG.STANDARD_CONCEPT = 'S'
AND   DRUG.INVALID_REASON IS NULL
GROUP BY DRUG.CONCEPT_ID,
         INGREDIENT_CONCEPT_ID,
         AMOUNT_VALUE,
         AMOUNT_UNIT_CONCEPT_ID,
         NUMERATOR_VALUE,
         NUMERATOR_UNIT_CONCEPT_ID,
         DENOMINATOR_VALUE,
         DENOMINATOR_UNIT_CONCEPT_ID,
         FORM.CONCEPT_ID
ORDER BY DRUG.CONCEPT_ID,
         INGREDIENT_CONCEPT_ID