SELECT drugcomp.concept_id AS drugcomp_concept_id,
       drugcomp.concept_name AS drugcomp_concept_name,
       drugcomp.domain_id AS drugcomp_domain_id,
       drugcomp.vocabulary_id AS drugcomp_vocabulary_id,
       drugcomp.concept_class_id AS drugcomp_concept_class_id,
       drugcomp.standard_concept AS drugcomp_standard_concept,
       drugcomp.concept_code AS drugcomp_concept_code,
       drugcomp.valid_start_date AS drugcomp_valid_start_date,
       drugcomp.valid_end_date AS drugcomp_valid_end_date,
       drugcomp.invalid_reason AS drugcomp_invalid_reason,
       strength.amount_value,
       strength.amount_unit_concept_id,
       amount_unit.concept_name AS amount_unit_concept_name,
       amount_unit.domain_id AS amount_unit_domain_id,
       amount_unit.vocabulary_id AS amount_unit_vocabulary_id,
       amount_unit.concept_class_id AS amount_unit_concept_class_id,
       amount_unit.standard_concept AS amount_unit_standard_concept,
       amount_unit.concept_code AS amount_unit_concept_code,
       amount_unit.valid_start_date AS amount_unit_valid_start_date,
       amount_unit.valid_end_date AS amount_unit_valid_end_date,
       amount_unit.invalid_reason AS amount_unit_invalid_reason,
       strength.numerator_value,
       strength.numerator_unit_concept_id,
       numerator_unit.concept_name AS numerator_unit_concept_name,
       numerator_unit.domain_id AS numerator_unit_domain_id,
       numerator_unit.vocabulary_id AS numerator_unit_vocabulary_id,
       numerator_unit.concept_class_id AS numerator_unit_concept_class_id,
       numerator_unit.standard_concept AS numerator_unit_standard_concept,
       numerator_unit.concept_code AS numerator_unit_concept_code,
       numerator_unit.valid_start_date AS numerator_unit_valid_start_date,
       numerator_unit.valid_end_date AS numerator_unit_valid_end_date,
       numerator_unit.invalid_reason AS numerator_unit_invalid_reason,
       strength.denominator_value,
       strength.denominator_unit_concept_id,
       denominator_unit.concept_name AS denominator_unit_concept_name,
       denominator_unit.domain_id AS denominator_unit_domain_id,
       denominator_unit.vocabulary_id AS denominator_unit_vocabulary_id,
       denominator_unit.concept_class_id AS denominator_unit_concept_class_id,
       denominator_unit.standard_concept AS denominator_unit_standard_concept,
       denominator_unit.concept_code AS denominator_unit_concept_code,
       denominator_unit.valid_start_date AS denominator_unit_valid_start_date,
       denominator_unit.valid_end_date AS denominator_unit_valid_end_date,
       denominator_unit.invalid_reason AS denominator_unit_invalid_reason,
       strength.box_size,
       strength.ingredient_concept_id
FROM @vocab.concept drugcomp
  INNER JOIN @vocab.drug_strength strength
    ON strength.drug_concept_id = drugcomp.concept_id
  LEFT OUTER JOIN @vocab.concept amount_unit
    ON strength.amount_unit_concept_id = amount_unit.concept_id
  LEFT OUTER JOIN @vocab.concept numerator_unit
    ON strength.numerator_unit_concept_id = numerator_unit.concept_id
  LEFT OUTER JOIN @vocab.concept denominator_unit
    ON strength.denominator_unit_concept_id = denominator_unit.concept_id
WHERE drugcomp.domain_id = 'Drug'
AND   drugcomp.vocabulary_id LIKE 'RxNorm%'
AND   drugcomp.concept_class_id = 'Clinical Drug Comp'
AND   drugcomp.standard_concept = 'S'
AND   drugcomp.invalid_reason IS NULL
GROUP BY drugcomp.concept_id,
         drugcomp.concept_name,
         drugcomp.domain_id,
         drugcomp.vocabulary_id,
         drugcomp.concept_class_id,
         drugcomp.standard_concept,
         drugcomp.concept_code,
         drugcomp.valid_start_date,
         drugcomp.valid_end_date,
         drugcomp.invalid_reason,
         strength.amount_value,
         strength.amount_unit_concept_id,
         amount_unit.concept_name,
         amount_unit.domain_id,
         amount_unit.vocabulary_id,
         amount_unit.concept_class_id,
         amount_unit.standard_concept,
         amount_unit.concept_code,
         amount_unit.valid_start_date,
         amount_unit.valid_end_date,
         amount_unit.invalid_reason,
         strength.numerator_value,
         strength.numerator_unit_concept_id,
         numerator_unit.concept_name,
         numerator_unit.domain_id,
         numerator_unit.vocabulary_id,
         numerator_unit.concept_class_id,
         numerator_unit.standard_concept,
         numerator_unit.concept_code,
         numerator_unit.valid_start_date,
         numerator_unit.valid_end_date,
         numerator_unit.invalid_reason,
         strength.denominator_value,
         strength.denominator_unit_concept_id,
         denominator_unit.concept_name,
         denominator_unit.domain_id,
         denominator_unit.vocabulary_id,
         denominator_unit.concept_class_id,
         denominator_unit.standard_concept,
         denominator_unit.concept_code,
         denominator_unit.valid_start_date,
         denominator_unit.valid_end_date,
         denominator_unit.invalid_reason,
         strength.box_size,
         strength.ingredient_concept_id
ORDER BY drugcomp.concept_id,
         strength.ingredient_concept_id