SELECT DISTINCT STRENGTH.DRUG_CONCEPT_ID AS CONCEPT_ID,
                ATC.CONCEPT_CODE AS ATC
FROM @vocab.DRUG_STRENGTH STRENGTH
INNER JOIN @vocab.CONCEPT_ANCESTOR ANCESTOR
    ON (ANCESTOR.DESCENDANT_CONCEPT_ID = STRENGTH.DRUG_CONCEPT_ID)
INNER JOIN @vocab.CONCEPT ATC
    ON (ATC.CONCEPT_ID = ANCESTOR.ANCESTOR_CONCEPT_ID) AND (ATC.VOCABULARY_ID = 'ATC')