SELECT RELATIONSHIP.RELATIONSHIP_ID,
       DRUG.CONCEPT_ID AS DRUG_CONCEPT_ID,
       DRUG.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
       DRUG.VOCABULARY_ID AS DRUG_VOCABULARY_ID,
       DRUG.CONCEPT_CLASS_ID AS DRUG_CONCEPT_CLASS_ID,
       DRUG.CONCEPT_CODE AS DRUG_CONCEPT_CODE,
       INGREDIENT.CONCEPT_ID AS INGREDIENT_CONCEPT_ID,
       CONCEPT_SYNONYM.CONCEPT_SYNONYM_NAME AS DRUG_SYNONYM_NAME
FROM @vocab.CONCEPT_RELATIONSHIP RELATIONSHIP
  LEFT OUTER JOIN @vocab.CONCEPT DRUG
    ON RELATIONSHIP.CONCEPT_ID_1 = DRUG.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT INGREDIENT
    ON RELATIONSHIP.CONCEPT_ID_2 = INGREDIENT.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT_SYNONYM
    ON DRUG.CONCEPT_ID = CONCEPT_SYNONYM.CONCEPT_ID
WHERE DRUG.CONCEPT_ID <> INGREDIENT.CONCEPT_ID
AND   (
		(RELATIONSHIP.RELATIONSHIP_ID = 'Maps to') OR
		(RELATIONSHIP.RELATIONSHIP_ID = 'Form of') OR
		(RELATIONSHIP.RELATIONSHIP_ID = 'ATC - RxNorm') OR
		(RELATIONSHIP.RELATIONSHIP_ID = 'Concept replaced by') OR
		(UPPER(RELATIONSHIP.RELATIONSHIP_ID) LIKE '%RXNORM EQ')
	  )
AND   (
		(DRUG.CONCEPT_CLASS_ID = 'Ingredient') OR
		(DRUG.CONCEPT_CLASS_ID = 'Precise Ingredient') OR
		(DRUG.CONCEPT_CLASS_ID = 'Substance') OR
		(DRUG.CONCEPT_CLASS_ID = 'ATC 5th') OR
		(DRUG.CONCEPT_CLASS_ID = 'ATC 4th') OR
		(DRUG.CONCEPT_CLASS_ID = 'Pharma/Biol Product') OR
		(DRUG.CONCEPT_CLASS_ID = '11-digit NDC') OR
		(DRUG.CONCEPT_CLASS_ID = '9-digit NDC')
      )
AND   UPPER(INGREDIENT.CONCEPT_CLASS_ID) LIKE '%INGREDIENT'
AND   INGREDIENT.STANDARD_CONCEPT = 'S'
ORDER BY RELATIONSHIP.RELATIONSHIP_ID,
         DRUG.CONCEPT_ID,
         CONCEPT_SYNONYM.CONCEPT_SYNONYM_NAME,
         INGREDIENT.CONCEPT_ID