SELECT DRUG.CONCEPT_ID AS DRUG_CONCEPT_ID,
       DRUG.CONCEPT_NAME AS DRUG_CONCEPT_NAME,
       DRUG.DOMAIN_ID AS DRUG_DOMAIN_ID,
       DRUG.VOCABULARY_ID AS DRUG_VOCABULARY_ID,
       DRUG.CONCEPT_CLASS_ID AS DRUG_CONCEPT_CLASS_ID,
       DRUG.STANDARD_CONCEPT AS DRUG_STANDARD_CONCEPT,
       DRUG.CONCEPT_CODE AS DRUG_CONCEPT_CODE,
       DRUG.VALID_START_DATE AS DRUG_VALID_START_DATE,
       DRUG.VALID_END_DATE AS DRUG_VALID_END_DATE,
       DRUG.INVALID_REASON AS DRUG_INVALID_REASON,
       FORM.CONCEPT_ID AS FORM_CONCEPT_ID,
       STRENGTH.AMOUNT_VALUE,
       STRENGTH.AMOUNT_UNIT_CONCEPT_ID,
       AMOUNT_UNIT.CONCEPT_NAME AS AMOUNT_UNIT_CONCEPT_NAME,
       AMOUNT_UNIT.DOMAIN_ID AS AMOUNT_UNIT_DOMAIN_ID,
       AMOUNT_UNIT.VOCABULARY_ID AS AMOUNT_UNIT_VOCABULARY_ID,
       AMOUNT_UNIT.CONCEPT_CLASS_ID AS AMOUNT_UNIT_CONCEPT_CLASS_ID,
       AMOUNT_UNIT.STANDARD_CONCEPT AS AMOUNT_UNIT_STANDARD_CONCEPT,
       AMOUNT_UNIT.CONCEPT_CODE AS AMOUNT_UNIT_CONCEPT_CODE,
       AMOUNT_UNIT.VALID_START_DATE AS AMOUNT_UNIT_VALID_START_DATE,
       AMOUNT_UNIT.VALID_END_DATE AS AMOUNT_UNIT_VALID_END_DATE,
       AMOUNT_UNIT.INVALID_REASON AS AMOUNT_UNIT_INVALID_REASON,
       STRENGTH.NUMERATOR_VALUE,
       STRENGTH.NUMERATOR_UNIT_CONCEPT_ID,
       NUMERATOR_UNIT.CONCEPT_NAME AS NUMERATOR_UNIT_CONCEPT_NAME,
       NUMERATOR_UNIT.DOMAIN_ID AS NUMERATOR_UNIT_DOMAIN_ID,
       NUMERATOR_UNIT.VOCABULARY_ID AS NUMERATOR_UNIT_VOCABULARY_ID,
       NUMERATOR_UNIT.CONCEPT_CLASS_ID AS NUMERATOR_UNIT_CONCEPT_CLASS_ID,
       NUMERATOR_UNIT.STANDARD_CONCEPT AS NUMERATOR_UNIT_STANDARD_CONCEPT,
       NUMERATOR_UNIT.CONCEPT_CODE AS NUMERATOR_UNIT_CONCEPT_CODE,
       NUMERATOR_UNIT.VALID_START_DATE AS NUMERATOR_UNIT_VALID_START_DATE,
       NUMERATOR_UNIT.VALID_END_DATE AS NUMERATOR_UNIT_VALID_END_DATE,
       NUMERATOR_UNIT.INVALID_REASON AS NUMERATOR_UNIT_INVALID_REASON,
       STRENGTH.DENOMINATOR_VALUE,
       STRENGTH.DENOMINATOR_UNIT_CONCEPT_ID,
       DENOMINATOR_UNIT.CONCEPT_NAME AS DENOMINATOR_UNIT_CONCEPT_NAME,
       DENOMINATOR_UNIT.DOMAIN_ID AS DENOMINATOR_UNIT_DOMAIN_ID,
       DENOMINATOR_UNIT.VOCABULARY_ID AS DENOMINATOR_UNIT_VOCABULARY_ID,
       DENOMINATOR_UNIT.CONCEPT_CLASS_ID AS DENOMINATOR_UNIT_CONCEPT_CLASS_ID,
       DENOMINATOR_UNIT.STANDARD_CONCEPT AS DENOMINATOR_UNIT_STANDARD_CONCEPT,
       DENOMINATOR_UNIT.CONCEPT_CODE AS DENOMINATOR_UNIT_CONCEPT_CODE,
       DENOMINATOR_UNIT.VALID_START_DATE AS DENOMINATOR_UNIT_VALID_START_DATE,
       DENOMINATOR_UNIT.VALID_END_DATE AS DENOMINATOR_UNIT_VALID_END_DATE,
       DENOMINATOR_UNIT.INVALID_REASON AS DENOMINATOR_UNIT_INVALID_REASON,
       STRENGTH.BOX_SIZE,
       STRENGTH.INGREDIENT_CONCEPT_ID
FROM @vocab.CONCEPT DRUG
  INNER JOIN @vocab.DRUG_STRENGTH STRENGTH
    ON STRENGTH.DRUG_CONCEPT_ID = DRUG.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT_RELATIONSHIP HAS_FORM
    ON DRUG.CONCEPT_ID = HAS_FORM.CONCEPT_ID_1
  LEFT OUTER JOIN @vocab.CONCEPT FORM
    ON HAS_FORM.CONCEPT_ID_2 = FORM.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT AMOUNT_UNIT
    ON STRENGTH.AMOUNT_UNIT_CONCEPT_ID = AMOUNT_UNIT.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT NUMERATOR_UNIT
    ON STRENGTH.NUMERATOR_UNIT_CONCEPT_ID = NUMERATOR_UNIT.CONCEPT_ID
  LEFT OUTER JOIN @vocab.CONCEPT DENOMINATOR_UNIT
    ON STRENGTH.DENOMINATOR_UNIT_CONCEPT_ID = DENOMINATOR_UNIT.CONCEPT_ID
WHERE DRUG.DOMAIN_ID = 'Drug'
AND   UPPER(DRUG.VOCABULARY_ID) LIKE 'RXNORM%'
AND   DRUG.CONCEPT_CLASS_ID = 'Clinical Drug'
AND   DRUG.STANDARD_CONCEPT = 'S'
-- AND   DRUG.INVALID_REASON IS NULL
AND   HAS_FORM.RELATIONSHIP_ID = 'RxNorm has dose form'
GROUP BY DRUG.CONCEPT_ID,
         DRUG.CONCEPT_NAME,
         DRUG.DOMAIN_ID,
         DRUG.VOCABULARY_ID,
         DRUG.CONCEPT_CLASS_ID,
         DRUG.STANDARD_CONCEPT,
         DRUG.CONCEPT_CODE,
         DRUG.VALID_START_DATE,
         DRUG.VALID_END_DATE,
         DRUG.INVALID_REASON,
         FORM.CONCEPT_ID,
         STRENGTH.AMOUNT_VALUE,
         STRENGTH.AMOUNT_UNIT_CONCEPT_ID,
         AMOUNT_UNIT.CONCEPT_NAME,
         AMOUNT_UNIT.DOMAIN_ID,
         AMOUNT_UNIT.VOCABULARY_ID,
         AMOUNT_UNIT.CONCEPT_CLASS_ID,
         AMOUNT_UNIT.STANDARD_CONCEPT,
         AMOUNT_UNIT.CONCEPT_CODE,
         AMOUNT_UNIT.VALID_START_DATE,
         AMOUNT_UNIT.VALID_END_DATE,
         AMOUNT_UNIT.INVALID_REASON,
         STRENGTH.NUMERATOR_VALUE,
         STRENGTH.NUMERATOR_UNIT_CONCEPT_ID,
         NUMERATOR_UNIT.CONCEPT_NAME,
         NUMERATOR_UNIT.DOMAIN_ID,
         NUMERATOR_UNIT.VOCABULARY_ID,
         NUMERATOR_UNIT.CONCEPT_CLASS_ID,
         NUMERATOR_UNIT.STANDARD_CONCEPT,
         NUMERATOR_UNIT.CONCEPT_CODE,
         NUMERATOR_UNIT.VALID_START_DATE,
         NUMERATOR_UNIT.VALID_END_DATE,
         NUMERATOR_UNIT.INVALID_REASON,
         STRENGTH.DENOMINATOR_VALUE,
         STRENGTH.DENOMINATOR_UNIT_CONCEPT_ID,
         DENOMINATOR_UNIT.CONCEPT_NAME,
         DENOMINATOR_UNIT.DOMAIN_ID,
         DENOMINATOR_UNIT.VOCABULARY_ID,
         DENOMINATOR_UNIT.CONCEPT_CLASS_ID,
         DENOMINATOR_UNIT.STANDARD_CONCEPT,
         DENOMINATOR_UNIT.CONCEPT_CODE,
         DENOMINATOR_UNIT.VALID_START_DATE,
         DENOMINATOR_UNIT.VALID_END_DATE,
         DENOMINATOR_UNIT.INVALID_REASON,
         STRENGTH.BOX_SIZE,
         STRENGTH.INGREDIENT_CONCEPT_ID
ORDER BY DRUG.CONCEPT_ID,
         FORM.CONCEPT_ID,
         STRENGTH.INGREDIENT_CONCEPT_ID